FROM python:3.12-slim

# Prevent Python from creating .pyc files
# and enable unbuffered logging
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Working directory inside container
WORKDIR /app

# System dependencies required by TensorFlow / image processing
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy FastAPI application
COPY api ./api

# Copy source modules used by the API
COPY src ./src

# Copy trained Baseline CNN
COPY artifacts/baseline_cnn/models/best_model.keras \
     ./artifacts/baseline_cnn/models/best_model.keras
COPY artifacts/preprocessing/class_mapping.json \
     ./artifacts/preprocessing/class_mapping.json

# FastAPI port
EXPOSE 8000

# Start FastAPI
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]